# This file is generated by setup_htmx.py

from typing import Any
from typing_extensions import TypedDict, Literal
from pydom.types.html.aria_props import AriaProps
from pydom.types.html.html_element import HTMLElement
from pydom.types.html.html_event_props import HTMLEventProps

SwapValues = Literal[
    "innerHTML",
    "outerHTML",
    "textContent",
    "beforebegin",
    "afterbegin",
    "beforeend",
    "afterend",
    "delete",
    "none",
]
TargetValues = Literal[
    "this",
    "closest ",
    "find ",
    "next",
    "next ",
    "previous",
    "previous ",
]
EventValues = Literal[
    "click",
    "submit",
    "change",
    # non-standard
    "load",
    "revealed",
    "intersect",
]
ParamsValues = Literal[
    "*",
    "none",
    "not ",
]

class HTMXProps(TypedDict, total=False, extra_items=Any):
    hx_get: str | None
    hx_post: str | None
    hx_push_url: str | Literal["true", "false"] | None
    hx_select: str | None
    hx_select_oob: str | None
    hx_swap: SwapValues | str | None
    hx_swap_oob: Literal[True] | SwapValues | str | None
    hx_target: TargetValues | str | None
    hx_trigger: EventValues | str | None
    hx_vals: str | None
    hx_boost: Literal[True, "true", "false"] | None
    hx_confirm: str | None
    hx_delete: str | None
    hx_disable: Literal[True] | None
    hx_disabled_elt: TargetValues | str | None
    hx_disinherit: str | None
    hx_encoding: str | None
    hx_ext: str | None
    hx_headers: str | None
    hx_history: Literal["false"] | None
    hx_history_elt: Literal[True] | None
    hx_include: TargetValues | str | None
    hx_indicator: TargetValues | str | None
    hx_inherit: str | None
    hx_params: ParamsValues | str | None
    hx_patch: str | None
    hx_preserve: Literal[True] | None
    hx_prompt: str | None
    hx_put: str | None
    hx_replace_url: Literal["true", "false"] | str | None
    hx_request: str | None
    hx_sync: str | None
    hx_validate: Literal["true", True] | None
    hx_vars: str | None

    # TODO: events
    # hx-on:htmx:*
    # hx-on::*
    # hx-on:*

class HTMXSSE(TypedDict, total=False):
    sse_connect: str
    sse_swap: str
    sse_close: str

class HTMXWebSocketExtension(TypedDict, total=False):
    ws_connect: str
    ws_send: str

class HTMXExtensions(HTMXSSE, HTMXWebSocketExtension):
    pass

class CustomAttributes(TypedDict, total=False):
    for_: str

# fmt:off
class HTMLElementProps(
    HTMLElement, AriaProps, HTMLEventProps,
    HTMXProps, HTMXExtensions,
    CustomAttributes
):
    pass
# fmt:on

    